version: 2

models:
    - name: fact_orders
      description: "orders selled"
      columns:
          - name: id
            description: "The primary key for this table"
          - name: first_name
            description: "name of the customer"
          - name: last_name
            description: "last name of the customer"