
version: 2

models:
    - name: dim_customers
      description: "dimension model for customers table"
      columns:
          - name: id
            description: "The primary key for this table"
          - name: first_name
            description: "name of the customer"
          - name: last_name
            description: "last name of the customer"
          - name: first_order_date
            description: "date of the first order requested by the customer"
          - name: most_recent_order_date
            description: "last order requested by the customer"
          - name: number_of_orders
            description: "number of orders requested by the customer"
          - name: total_spent
            description: "total spend on lifetime customer"
